# Server Port
server.port=8080

# Application Name
spring.application.name=train-ticket-booking

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ve_tau?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678

# JPA / Hibernate Settings for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging SQL
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT Configuration
jwt.signerKey=18012026_TrainTicketBookingSystemSecretKeyForJWTAuthentication_99999999
jwt.valid-duration=900
jwt.refreshable-duration=604800

# VNPAY SANDBOX CONFIGURATION
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=http://localhost:8080/api/v1/payments/vnpay-callback
vnpay.tmnCode=91X4SC1S
vnpay.secretKey=FCCBXGAWHQTFYBDHVKHURVBPXNFUSYCB
vnpay.version=2.1.0
vnpay.command=pay

# MOMO CONFIGURATION
DEV_MOMO_ENDPOINT=https://test-payment.momo.vn/v2/gateway/api
DEV_ACCESS_KEY=mTCKt9W3eU1m39TW
DEV_PARTNER_CODE=MOMOLRJZ20181206
DEV_SECRET_KEY=SetA5RDnLHvt51AULf51DyauxUo3kDU6
